In [42]:
!pip install gensim


Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
^C
ERROR: Operation cancelled by user


In [ ]:
# Load your text file
with open('street_names.txt', 'r', encoding='utf-8') as file:
    sentences = [line.split() for line in file.readlines()]

In [46]:
import gensim
from gensim.models import Word2Vec



# Create Word2Vec model
model = Word2Vec(sentences, vector_size=256, window=5, min_count=1, workers=4, epochs=100)

# Save the model for later use
# model.save("word2vec_model.model")

In [60]:
# Example sentence
sentence = ["الغربية", "طنطا", "رضوان", "حسن", "شارع"]
context_words = [word for word in sentence if word in model.wv.key_to_index]

In [61]:
context_words

['الغربية', 'طنطا', 'رضوان', 'حسن', 'شارع']

In [62]:
import numpy as np

In [63]:
context_vector = np.mean([model.wv[word] for word in context_words], axis=0)

In [64]:
context_vector.shape

(256,)

In [74]:
x = "شارع مكتب العمل ميت غمر الاهلي"
sentence = x.split()


nom = len(sentence) - 1 

for i, word in enumerate(sentence):
    distance = 0.0
    for j, word2 in enumerate(sentence):
        if i == j : continue
        distance += float(np.dot(model.wv[word], model.wv[word2]))
    score = distance / nom
    print(word, score)
        
        



شارع -105.91275901794434
مكتب 1.640293502807617
العمل 2.2011404037475586
ميت -47.57247123718262
غمر -44.773319244384766
الاهلي 3.082703971862793


In [73]:
x = "شارع مكتب العمل ميت غمر الدقهلية"
sentence = x.split()

nom = len(sentence) - 1 

for i, word in enumerate(sentence):
    distance = 0.0
    for j, word2 in enumerate(sentence):
        if i == j : continue
        distance +=  float(np.dot(model.wv[word], model.wv[word2]))
    score = distance / nom
    print(word, score)
        
        



شارع -87.60216064453125
مكتب -15.063938903808594
العمل -5.49685115814209
ميت -39.99383602142334
غمر -41.98771171569824
الدقهلية 7.3553211212158205


In [75]:
np.dot(model.wv["الدقهلية"], model.wv["غمر"])

17.368052

In [77]:
np.dot(model.wv["العمل"], model.wv["غمر"])

69.74074

In [1]:
import nltk
from nltk.tokenize import word_tokenize
from collections import defaultdict

# Read the text file
with open('street_names.txt', 'r', encoding='utf-8') as file:
    text = file.read()

# Download necessary NLTK data files (run this once)
nltk.download('punkt')

tokens = word_tokenize(text)

# Create a mapping of words to unique IDs
word_to_id = {}
id_to_word = {}

for idx, word in enumerate(set(tokens)):
    word_to_id[word] = idx
    id_to_word[idx] = word

# Display the mappings
print("Word to ID mapping:")
for word, id in word_to_id.items():
    print(f"{word}: {id}")

print("\nID to Word mapping:")
for id, word in id_to_word.items():
    print(f"{id}: {word}")

[nltk_data] Downloading package punkt to /home/mohamed/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Word to ID mapping:
العذراء: 0
المسلميه: 1
وافى: 2
الصناديلي: 3
الصربوط: 4
سكرة: 5
البقريه: 6
شربات: 7
روزيتا: 8
الجنوب: 9
النجارى: 10
برانق: 11
الشرابي: 12
رمزي: 13
الهدايا: 14
زغيبى: 15
البرى: 16
بلطيم: 17
قتة: 18
لاوندي: 19
العايه: 20
الضرغامي: 21
عزار: 22
البزوناجى: 23
القطاع: 24
المرن: 25
التطور: 26
البستان: 27
بلقيس: 28
الثريا: 29
العقدة: 30
شرشرة: 31
الخوام: 32
هبه: 33
الريحانى: 34
المناشي: 35
نظمى: 36
القطورى: 37
المطواعة: 38
النيال: 39
مخ: 40
جنيفا: 41
الخرطه: 42
عب: 43
الطويهي: 44
آلاف: 45
الزوايده: 46
ليلا: 47
مكتب: 48
مندور: 49
الدبيكى: 50
الشرطه: 51
الارنب: 52
الحيت: 53
اورمان: 54
الربيعة: 55
الاحياء: 56
المعبر: 57
الشرقيه: 58
البشاشه: 59
ايما: 60
اعضاء: 61
تكش: 62
الزرازريواحد: 63
راعى: 64
العواجات: 65
اشمنت: 66
التاجوري: 67
الصاحى: 68
الحجريه: 69
الشنيني: 70
أمينه: 71
المعلومات: 72
كريشه: 73
الخليجى: 74
الشربيني: 75
الموكليه: 76
البساطي: 77
شنن: 78
شماعه: 79
الدوبك: 80
القممي: 81
الريات: 82
قلتى: 83
حمدته: 84
الحواويش: 85
طاقة: 86
الثلاثاء: 87
سيوه: 88
الريحاني: 89
كمبل:

In [2]:
word_to_id["الجديدة"]

15532

In [41]:
set_tokens  = set(tokens)

In [43]:
set_tokens

{'جسر',
 'ونيس',
 'جراد',
 'بلاسي',
 'للتخطيط',
 'مزار',
 'ممنون',
 'كسبه',
 'عداء',
 'فيض',
 'شماته',
 'الحساميه',
 'تاون',
 'البنجاوى',
 'اللحم',
 'نشابه',
 'عربود',
 'لقانة',
 'انتاج',
 'الاجنبيه',
 'البابلي',
 'عطفه',
 'الجاجى',
 'الكواكبى',
 'دنشواي',
 'السمرى',
 'الحجاوى',
 'المرازيق',
 'قنطار',
 'الغرب',
 'السروجي',
 'الشامات',
 'النقمة',
 'الدوبلى',
 'الزيني',
 'ديميترى',
 'المفتي',
 'الذراع',
 'سعدونى',
 'توفيق',
 'الموزايكو',
 'الداخل',
 'البلاس',
 'مرزبان',
 'الامشيطى',
 'نسب',
 'التومه',
 'الشيتاني',
 'البلاحين',
 'أمر',
 'الفحام',
 'الدويرى',
 'النوبرى',
 'العواني',
 'الضوي',
 'البرق',
 'اخشيد',
 'ميزان',
 'الرمايه',
 'البوشه',
 'الزقزقة',
 'سمره',
 'السوبكى',
 'القمانه',
 'الشيخية',
 'البساينه',
 'الشربتلى',
 'الكهرباء',
 'جبانى',
 'بديع',
 'روجينا',
 'شويطر',
 'السجينى',
 'عطيفة',
 'جودت',
 'السندبيسي',
 'الهاشم',
 'الرجمه',
 'الكينج',
 'مكتى',
 'صبيحى',
 'داوود',
 'رماح',
 'سندنهور',
 'باسلي',
 'الفلاح',
 'الكشاف',
 'فايقه',
 'مخلوف',
 'مفرخه',
 'الشرقاية',
 'الدوانى',


In [44]:
import pickle
with open('address_wrods_set.pkl', 'wb') as f:
    pickle.dump(set_tokens, f)

In [4]:
id_to_word[0]

'جسر'

In [5]:
word_to_id["طنطا"]

17909

In [33]:
from collections import Counter
from collections import defaultdict

def get_forward_backward_probabilites(filename):
    forward_occurance = []
    backward_occurance = []
    word_occurance = []

    with open (filename, "r") as file:
        for line in file.readlines():
            words_list =line.split(" ") 
            words_list = list(map(lambda x: x.strip(), words_list))
            for i, word in enumerate(words_list):
                word_occurance.append(word)
                for j in range(i+1, len(words_list)):
                    forward_occurance.append( (word, words_list[j]) )
                    backward_occurance.append( (words_list[j], word) )



    forward_frequncies = Counter(forward_occurance)
    backward_frequncies = Counter(backward_occurance)
    word_frequncies = Counter(word_occurance)

    forward_probabilities = defaultdict(float)
    backward_probabilities = defaultdict(float)


    for (w1, w2), count in forward_frequncies.items():
        forward_probabilities[(w1, w2)] = count / word_frequncies[w1]

    for (w1, w2), count in backward_frequncies.items():
        backward_probabilities[(w1, w2)] = count / word_frequncies[w1]

    return forward_probabilities, backward_probabilities


In [ ]:
from collections import Counter
from collections import defaultdict

def get_forward_backward_probabilites(filename):
    forward_occurance = []
    backward_occurance = []
    word_occurance = []

    with open (filename, "r") as file:
        for line in file.readlines():
            words_list =line.split(" ") 
            words_list = list(map(lambda x: x.strip(), words_list))
            for i, word in enumerate(words_list):
                word_occurance.append(word)
                for j in range(i+1, len(words_list)):
                    forward_occurance.append( (word, words_list[j]) )
                    backward_occurance.append( (words_list[j], word) )



    forward_frequncies = Counter(forward_occurance)
    backward_frequncies = Counter(backward_occurance)
    word_frequncies = Counter(word_occurance)

    forward_probabilities = defaultdict(float)
    backward_probabilities = defaultdict(float)


    for (w1, w2), count in forward_frequncies.items():
        forward_probabilities[(w1, w2)] = count / word_frequncies[w1]

    for (w1, w2), count in backward_frequncies.items():
        backward_probabilities[(w1, w2)] = count / word_frequncies[w1]

    return forward_probabilities, backward_probabilities


In [38]:
f_p, b_p = get_forward_backward_probabilites("street_names.txt")

In [39]:
import pickle
with open('forward_bacward_probs.pkl', 'wb') as f:
    pickle.dump((f_p, b_p), f)

In [12]:
x = "شارع مكتب العمل ميت غمر الاهلي"

In [14]:
tokens = x.split()
ids = list(map(lambda x: word_to_id[x], tokens))
ids

[14204, 19083, 6145, 5606, 19090, 10025]

In [45]:
K = 3
bests = []
for i, idi in enumerate(ids):
    cur_prob = np.ones(19496)
    for j, idj in enumerate(ids):
        if i == j :
            continue

        if j < i :
            cur_prob *= f[idj, :]

        if j > i :
            cur_prob *= b[idj, :]

    best = cur_prob.argsort()[-5:][::-1]
    for be in list(best):
        print(id_to_word[be], end=" ")
    print()
    bests.append(best)








TypeError: unhashable type: 'slice'

In [32]:
bests

[array([14204,  6060,  4555, 19246,  3834,   185,  5097,  4014, 12356,
         6494,  6495,  6496,  6497, 19495,  6492,  6498,  6499,  6500,
         6501,  6502]),
 array([14204,  6060,   185, 19246,  3834,  4014, 19495,  6498,  6495,
         6496,  6497,  6500,  6499,  6493,  6501,  6502,  6503,  6504,
         6505,  6494]),
 array([19495,  6501,  6494,  6495,  6496,  6497,  6498,  6499,  6500,
         6502,  6397,  6503,  6504,  6505,  6506,  6507,  6508,  6509,
         6493,  6492]),
 array([19495,  6501,  6494,  6495,  6496,  6497,  6498,  6499,  6500,
         6502,  6397,  6503,  6504,  6505,  6506,  6507,  6508,  6509,
         6493,  6492]),
 array([19495,  6501,  6494,  6495,  6496,  6497,  6498,  6499,  6500,
         6502,  6397,  6503,  6504,  6505,  6506,  6507,  6508,  6509,
         6493,  6492]),
 array([ 5676,  3924,  8776, 14343,  3841,  5020, 12034, 10590,  2059,
         8383, 14958, 13277, 11262,  1247,   933,  4403, 17132,  4752,
        17502, 12471])]

In [ ]:
id_to_word()